# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: About Me
    url: '#about'
    weight: 10
  - name: Publications
    url: '#publications'
    weight: 20
  - name: Talks
    url: '#talks'
    weight: 30
  - name: Teaching
    url: '#teaching'
    weight: 40
  - name: Course Materials
    url: 'materials/about/'
    weight: 50 
    #identifier: 'm'
    #- name: Applied Calculus
    #url: 'materials/math1106/'
    #parent: 'm'
    #- name: Discrete Math
    #url: 'materials/cs2800/'
    #parent: 'm'
    #- name: Linear Algebra
    #url: 'materials/math2210/'
    #parent: 'm'

  - name: CV
    url: 'uploads/resume.pdf'
    weight: 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
