name: Publish Site

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout master
      uses: actions/checkout@v1
      with:
        submodules: true

    - name: Hugo Deploy GitHub Pages
      uses: benmatselby/hugo-deploy-gh-pages@master
      env:
        HUGO_VERSION: 0.91.0
        TARGET_REPO: maeichho/maeichho.github.io
        TARGET_BRANCH: main
        TOKEN: ${{ secrets.SITE_TOKEN }}
        HUGO_EXTENDED: true
        HUGO_FLAGS: --verbose  
